Add an example of beamjob and an example of xgboosttrainingjob
t9k/tutorial-examples pull request #20
Opened 2023-02-06 12:13 UTC by xyxxxxx

* Beam 的示例使用单词计数示例程序
* XGBoost 的示例从 https://github.com/kubeflow/xgboost-operator/tree/master/config/samples/xgboost-dist 修改得到，支持 GPU 训练
* t9kpublic 镜像已上传

2023-02-06 12:23 UTC, ppkube requested changes

2023-02-06 12:23 UTC, ppkube commented on job/xgboosttrainingjob/distributed/job.yaml
> +                  cpu: 100m
100m looks incorrect - you are running a compute-intensive ML job

2023-02-06 12:23 UTC, ppkube commented on job/xgboosttrainingjob/distributed/job.yaml
> +                  cpu: 100m
ditto

2023-02-06 12:23 UTC, ppkube commented on job/xgboosttrainingjob/distributed/job_gpu.yaml
> +                  cpu: 100m
ditto

2023-02-06 12:23 UTC, ppkube commented on job/xgboosttrainingjob/distributed/job_gpu.yaml
> +                  cpu: 100m
ditto

2023-02-06 12:23 UTC, ppkube commented on job/xgboosttrainingjob/distributed/job_gpu_t9ksched.yaml
> +                  cpu: 100m
ditto

2023-02-07 06:51 UTC, xyxxxxx commented on job/xgboosttrainingjob/distributed/README.md
> +kubectl create -f job_gpu.yaml
实测支持 GPU

2023-02-07 06:59 UTC, xyxxxxx commented on job/xgboosttrainingjob/distributed/job.yaml
> +                  cpu: 100m
全部改为 `cpu: 1, memory: 1Gi`

这个示例计算量太小，差不多1s跑完

2023-02-07 07:02 UTC, ppkube approved these changes
lgtm

2023-02-07 07:03 UTC, merged